### ISSUE TITLE
from model import preprocess_img, predict_result generating syntax error

### ISSUE THREAD

**Issue by Tigger36** [Sachin-crypto/Flask_Image_Recognition#2]
Is it possible the package name was changed? If so does anyone know what the new name is? 

Thanks and Regards

**Comment by Sachin-crypto** [comment]
preprocess_img and predict_result functions are inside the model.py file. from model import preprocess_img, predict_result means we are importing both functions from the model.py file.

Clone this repo again and install the requirement.txt file and run the server, you won't get any errors.

**Comment by Tigger36** [comment]
that did work, thank you! Unfortunately, now i'm running into another issue where I keep getting the message "the file cannot be processed". Do the images need to be a specific file type?

**Comment by Sachin-crypto** [comment]
Yeah, the image format should be .jpeg or .jpg
